project:
  type: website
  output-dir: docs

# Check out https://beamilz.com/posts/2022-06-05-creating-a-blog-with-quarto/en/#add-content-in-your-blog for some cool ideas about how to configure and add content to blog

website:
  title: "Ungrammetical Correctors Society"
  page-footer:
    left: "Blog made [Quarto](https://quarto.org/), by Antonio Páez. License: [CC BY-NC-ND 4.0](http://creativecommons.org/licenses/by-nc-nd/4.0/)."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/paezha
      - icon: mastodon
        href: https://mastodon.online/@paezha
      - icon: rss
        href: index.xml
      - text: CV
        href: https://paezha.github.io/Official-CV/
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

comments:
  giscus:
    repo: paezha/ungrammetical-correctors-society

execute:
  freeze: true


