project:
  type: website
  output-dir: docs

website:
  title: "ungrammetical-correctors-society"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/paezha
      - icon: mastodon
        href: https://mastodon.online/@paezha
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



